name: Components / Debug toolbar

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'pnpm-lock.yaml'
      - 'toolbar/**'
      - '!toolbar/**README.md'

defaults:
  run:
    working-directory: toolbar

concurrency:
  group: clients-typescript-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify_formatting:
    name: Check formatting & linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run check-styleguide
  check_types:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck
